In [151]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile

In [232]:
# Keeps first row of header and drops the other 2 header rows.
# Drops the blank rows and the total row since it is redundant.
# Fillna(0) and replace.({'**': 0}) replaced NaN and ** values with zeros.
Florida_data= pd.read_excel('Resources/16zp10fl.xls', sheetname='Sheet1', header=3)
Florida_data=Florida_data.drop(Florida_data.index[0:3])
Florida_data=Florida_data.rename(columns= {"ZIP\ncode [1]": "Zip Code"})
Florida_data=Florida_data.dropna(how="all")
Florida_data=Florida_data.dropna(subset=["Size of adjusted gross income"])
Florida_data=Florida_data.fillna(0)
Florida_data=Florida_data.replace({'**': 0})
    
# Rename the income brackets.    
Florida_data["Size of adjusted gross income"]= \
Florida_data["Size of adjusted gross income"].replace({ \
          "$1 under $25,000": "Under $25000", 
          "$25,000 under $50,000": "$25000 to $50000",
          "$50,000 under $75,000": "$50,000 to $75,000", 
          "$75,000 under $100,000": "$75,000 to $100,000",
          "$100,000 under $200,000": "$100,000 to $200,000",
          "$200,000 or more": "Over $200000"
          } 
          )

# Modified Zip Code Excel Sheet.
Florida_zip=pd.read_excel('Resources/Zip_Codes.xlsx')
Florida_zip=Florida_zip.rename(columns={"zip": "Zip Code", "primary_city": "City"})


# Turns Zip Code variable into integers for both sets so it will merge properly.
Florida_data["Zip Code"]=Florida_data["Zip Code"].astype(int)
Florida_zip["Zip Code"]=Florida_zip["Zip Code"].astype(int)


# Merges both on Zip Codes.
Florida_complete=pd.merge(Florida_zip, Florida_data, on='Zip Code')


# Renaming columns - Control + / to uncomment everything
Florida_complete=Florida_complete.rename(columns={                                                  
"Number of volunteer prepared returns [2]": "Total Number of volunteer prepared returns",
"Unnamed: 10": "Number of volunteer income tax assistance prepared returns",                                                  
"Unnamed: 11": "Number of tax counseling for the elderly prepared returns",                                                  
"Unnamed: 12": "Number of volunteer prepared returns with Earned Income Credit",                                                                                                   
"Number of elderly returns [3]": "Number of elderly returns",                                                  
"Adjusted gross income (AGI) [4]": "Adjusted gross income (AGI)",                                                  
"Total income": "Total income: Number of returns",                                                  
"Unnamed: 18": "Total income: Amount",                                                  
"Salaries and wages in AGI": "Salaries and wages in AGI: Number of returns",                                                  
"Unnamed: 20": "Salaries and wages in AGI: Amount",                                                  
"Taxable interest": "Taxable interest: Number of returns",                                                  
"Unnamed: 22": "Taxable interest: Amount",                                                  
"Ordinary dividends": "Ordinary dividends: Number of returns",                                                  
"Unnamed: 24": "Ordinary dividends: Amount",                                                  
"Qualified dividends [5]": "Qualified dividends: Number of returns",                                                  
"Unnamed: 26": "Qualified dividends: Amount",                                                  
"State and local income tax refunds\n": "State and local income tax refunds: Number of returns",                                                  
"Unnamed: 28": "State and local income tax refunds: Number of returns",                                                  
"Business or profession\net income": "Business or profession net income: Number of returns",                                                  
"Unnamed: 30": "Business or profession net income: Amount",
"Net capital gain (less loss) in AGI": "Net capital gain in AGI: Number of returns",                                                  
"Unnamed: 32": "Net capital gain in AGI: Amount",                                                  
"Taxable individual retirement\narrangement distributions": "Taxable individual retirement arrangement distributions: Number of returns",                                                  
"Unnamed: 34": "Taxable individual retirement arrangement distributions: Amount",                                                  
"Pensions and annuities in AGI": "Pensions and annuities in AGI: Number of returns",                                                  
"Unnamed: 36": "Pensions and annuities in AGI: Amount",                                                  
"Number of \nfarm returns": "Number of farm returns",
"Business or profession\nnet income (less loss)":"Business or profession net income: Number of returns",
"Unemployment compensation [6]": "Unemployment compensation: Number of returns",
"Unnamed: 39": "Unemployment compensation: Amount",
"Taxable Social Security benefits": "Taxable Social Security benefits: Number or returns",                                                  
"Unnamed: 41": "Taxable Social Security benefits: Amount",                                                  
"Partnership/S-corp net income (less loss)": "Partnership/S-corp net income: Number of returns",                                                  
"Unnamed: 43": "Partnership/S-corp net income: Amount",                                                  
"Total statuory adjustments": "Total statuory adjustments: Number of returns",                                                  
"Unnamed: 45": "Total statuory adjustments: Amount",                                                  
"Educator expenses": "Educator expenses: Number of returns",                                                  
"Unnamed: 47": "Educator expenses: Amount",                                                  
"Self-employed (Keogh) retirement plans": "Self-employed (Keogh) retirement plans: Number of returns",                                                  
"Unnamed: 49": "Self-employed (Keogh) retirement plans: Amount",                                                  
"Self-employed health insurance deduction": "Self-employed health insurance deduction: Number of returns",
"Unnamed: 51": "Self-employed health insurance deduction: Amount",                                                  
"Individual retirement arrangement payments": "Individual retirement arrangement payments: Number of returns",                                                  
"Unnamed: 53": "Individual retirement arrangement payments: Amount",                                                  
"Student loan interest deduction": "Student loan interest deduction: Number of returns",                                                  
"Unnamed: 55": "Student loan interest deduction: Amount",                                                  
"Tuition and fees deduction": "Tuition and fees deduction: Number of returns",                                                  
"Unnamed: 57": "Tuition and fees deduction: Amount",                                                  
"Domestic production activities deduction": "Domestic production activities deduction: Number of returns",                                                  
"Unnamed: 59": "Domestic production activities deduction: Amount",                                                  
"Total itemized deductions": "Total itemized deductions: Number of returns",                                                  
"Unnamed: 61": "Total itemized deductions: Amount",
"Unnamed: 62": "Total itemized deductions: Amount of AGI",
"Total medical and dental \nexpenses deduction": "Total medical and dental expenses deduction: Number of returns",
"Unnamed: 64": "Total medical and dental expenses deduction: Amount",                                                  
"State and local income taxes": "State and local income taxes: Number of returns",                                                  
"Unnamed: 66": "State and local income taxes: Amount",                                                  
"State and local general sales taxes": "State and local general sales taxes: Number of returns",                                                  
"Unnamed: 68": "State and local general sales taxes: Amount",                                                  
"Real estate taxes": "Real estate taxes: Number of returns",                                                  
"Unnamed: 70": "Real estate taxes: Amount",                                                  
"Personal property taxes": "Personal property taxes: Number of returns",                                                  
"Unnamed: 72": "Personal property taxes: Amount",                                                  
"Total taxes paid": "Total taxes paid: Number of returns",                                                  
"Unnamed: 74": "Total taxes paid: Amount",
"Home mortgage interest paid ": "Home mortgage interest paid: Number of returns",
"Unnamed: 76": "Home mortgage interest paid: Amount",                                                  
"Home mortgage interest paid \nfrom personal seller": "Home mortgage interest paid from personal seller: Number of returns",                                                  
"Unnamed: 78": "Home mortgage interest paid from personal seller: Amount",                                                  
"Deductible points": "Deductible points: Number of returns",                                                  
"Unnamed: 80": "Deductible points: Amount",                                                  
"Qualified mortgage insurance premiums": "Qualified mortgage insurance premiums: Number of returns",                                                  
"Unnamed: 82": "Qualified mortgage insurance premiums: Amount",                                                  
"Investment interest paid": "Investment interest paid: Number of returns",                                                  
"Unnamed: 84": "Investment interest paid: Amount",                                                  
"Total charitable contributions": "Total charitable contributions: Number of returns",                                                  
"Unnamed: 86": "Total charitable contributions: Amount",
"Net limited miscellaneous deduction": "Net limited miscellaneous deduction: Number of returns",
"Unnamed: 88": "Net limited miscellaneous deduction: Amount",                                                  
"Other non-limited \nmiscellaneous deduction": "Other non-limited miscellaneous deduction: Number of returns",                                                  
"Unnamed: 90": "Other non-limited miscellaneous deduction: Amount",                                                  
"Taxable income": "Taxable income: Number of returns",                                                  
"Unnamed: 92": "Taxable income: Amount",                                                  
"ncome tax before credits": "ncome tax before credits: Number of returns",                                                  
"Unnamed: 94": "ncome tax before credits: Amount",                                                  
"Alternative minimum tax": "Alternative minimum tax: Number of returns",                                                  
"Unnamed: 96": "Alternative minimum tax: Amount",                                                  
"Excess advance \npremium tax credit repayment": "Excess advance premium tax credit repayment: Number of returns",                                                  
"Unnamed: 98": "Excess advance premium tax credit repayment: Amount",
"Total tax credits": "Total tax credits: Number of returns",
"Unnamed: 100": "Total tax credits: Amount",                                                  
"Foreign tax credit": "Foreign tax credit: Number of returns",                                                  
"Unnamed: 102": "Foreign tax credit: Amount",                                                  
"Child and dependent care credit": "Child and dependent care credit: Number of returns",                                                  
"Unnamed: 104": "Child and dependent care credit: Amount",                                                  
"Nonrefundable education credit": "Nonrefundable education credit: Number of returns",                                                  
"Unnamed: 106": "Nonrefundable education credit: Amount",                                                  
"Retirement savings contributions credit": "Retirement savings contributions credit: Number of returns",                                                  
"Unnamed: 108": "Retirement savings contributions credit: Amount",                                                  
"Child tax credit": "Child tax credit: Number of returns",                                                  
"Unnamed: 110": "Child tax credit: Amount",
"Residential energy tax credit": "Residential energy tax credit: Number of returns",
"Unnamed: 112": "Residential energy tax credit: Amount",                                                  
"Self-employment tax": "Self-employment tax: Number of returns",                                                  
"Unnamed: 114": "Self-employment tax: Amount",                                                  
"Total premium tax credit": "Total premium tax credit: Number of returns",                                                  
"Unnamed: 116": "Total premium tax credit: Amount",                                                  
"Advance premium tax credit": "Advance premium tax credit: Number of returns",                                                  
"Unnamed: 118": "Advance premium tax credit: Amount",                                                  
"Health care individual \nresponsibility payment": "Health care individual responsibility payment: Number of returns",           
"Unnamed: 120": "Health care individual responsibility payment: Amount",                                                  
"Total tax payments": "Total tax payments: Number of returns",            
"Unnamed: 122": "Total tax payments: Amount",                                                  
"Earned income credit [7]": "Earned income credit: Number of returns",                                                  
"Unnamed: 124": "Earned income credit: Amount",
"Excess earned income credit \n(refundable) [8]": "Excess earned income credit (refundable): Number or returns",
"Unnamed: 126": "Excess earned income credit (refundable): Amount",                                                  
"Additional child tax credit": "Additional child tax credit: Number of returns",                                                  
"Unnamed: 128": "Additional child tax credit: Amount",                                                  
"Refundable education credit": "Refundable education credit: Number of returns",                                                  
"Unnamed: 130": "Refundable education credit: Amount",                                                  
"Net premium tax credit": "Net premium tax credit: Number of returns",                                                  
"Unnamed: 132": "Net premium tax credit: Amount",                                                  
"Income tax [9]": "Income tax: Number of returns",                                                  
"Unnamed: 134": "Income tax: Amount",                                                  
"Total tax liability [10]": "Total tax liability: Number of returns",                                                  
"Unnamed: 136": "Total tax liability: Amount",
"Total additional Medicare tax": "Total additional Medicare tax: Number of returns",
"Unnamed: 138": "Total additional Medicare tax: Amount",                                                  
"Net investment income tax": "Net investment income tax: Number of returns",                                                  
"Unnamed: 140": "Net investment income tax: Amount",                                                  
"Tax due at time of filing [11]": "Tax due at time of filing: Number of returns",                                                  
"Unnamed: 142": "Tax due at time of filing: Amount",                                                  
"Overpayments refunded [12]": "Overpayments refunded: Number of returns",                                                  
"Unnamed: 144": "Overpayments refunded: Amount",                                                  
}
)

In [237]:
# Drops zip codes to just yield cities.
Florida_cities=Florida_complete
Florida_cities=Florida_cities.drop("Zip Code", axis=1)
print(len(Florida_cities))

5502

In [235]:
# Miami prototype total.
# Income rows are not in the original order as they are sorted by ascending order.
# This can be fixed later.
Miami_stats=Florida_cities.loc[Florida_cities["City"]=="Miami",:]
Miami_stats=Miami_stats.groupby(['City', 'Size of adjusted gross income']).sum()
#print(len(Miami_stats.columns.values))
Miami_stats.head(10)

                                     Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                     63830.0
      $25000 to $50000                        212010.0
      $50,000 to $75,000                       90440.0
      $75,000 to $100,000                      46890.0
      Over $200000                             30320.0
      Under $25000                            418500.0

                                     Number of single returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                            13890.0
      $25000 to $50000                               106680.0
      $50,000 to $75,000                              39660.0
      $75,000 to $100,000                             15890.0
      Over $200000                                     4520.0
      Under $25000                                   267380.0

                                     Number of joint returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                           43260.0
      $25000 to $50000                               44680.0
      $50,000 to $75,000                             28350.0
      $75,000 to $100,000                            22010.0
      Over $200000                                   23640.0
      Under $25000                                   48950.0

                                     Number of head of household returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                        5980.0
      $25000 to $50000                                           55510.0
      $50,000 to $75,000                                         19490.0
      $75,000 to $100,000                                         7700.0
      Over $200000                                                1250.0
      Under $25000                                               96550.0

                                     Number with paid preparer's signature  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                         44770.0
      $25000 to $50000                                            146860.0
      $50,000 to $75,000                                           62350.0
      $75,000 to $100,000                                          32440.0
      Over $200000                                                 24700.0
      Under $25000                                                295380.0

                                     Number of exemptions  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                       163800.0
      $25000 to $50000                           384940.0
      $50,000 to $75,000                         174570.0
      $75,000 to $100,000                        101760.0
      Over $200000                                84490.0
      Under $25000                               625310.0

                                     Number of dependents  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                        56800.0
      $25000 to $50000                           129190.0
      $50,000 to $75,000                          55880.0
      $75,000 to $100,000                         32920.0
      Over $200000                                30520.0
      Under $25000                               202240.0

                                     Total Number of volunteer prepared returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                    0
      $25000 to $50000                                                     2070
      $50,000 to $75,000                                                     30
      $75,000 to $100,000                                                     0
      Over $200000                                                            0
      Under $25000                                                         6150

                                     Number of volunteer income tax assistance prepared returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                           0
      $25000 to $50000                                                            1850
      $50,000 to $75,000                                                            30
      $75,000 to $100,000                                                            0
      Over $200000                                                                   0
      Under $25000                                                                5160

                                     Number of tax counseling for the elderly prepared returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                           0
      $25000 to $50000                                                             220
      $50,000 to $75,000                                                             0
      $75,000 to $100,000                                                            0
      Over $200000                                                                   0
      Under $25000                                                                1020

                                     Number of volunteer prepared returns with Earned Income Credit  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                           0
      $25000 to $50000                                                               0
      $50,000 to $75,000                                                             0
      $75,000 to $100,000                                                            0
      Over $200000                                                                   0
      Under $25000                                                                2240

                                     Number of refund anticipation loan returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                  0.0
      $25000 to $50000                                                   1020.0
      $50,000 to $75,000                                                    0.0
      $75,000 to $100,000                                                   0.0
      Over $200000                                                          0.0
      Under $25000                                                       3150.0

                                     Number of refund anticipation check returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                4200.0
      $25000 to $50000                                                   46000.0
      $50,000 to $75,000                                                 13520.0
      $75,000 to $100,000                                                 4920.0
      Over $200000                                                          30.0
      Under $25000                                                       87930.0

                                     Number of elderly returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                             16240.0
      $25000 to $50000                                 31100.0
      $50,000 to $75,000                               17820.0
      $75,000 to $100,000                              11370.0
      Over $200000                                      8670.0
      Under $25000                                     63730.0

                                     Adjusted gross income (AGI)  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                             8681001.0
      $25000 to $50000                                 7526750.0
      $50,000 to $75,000                               5518085.0
      $75,000 to $100,000                              4048818.0
      Over $200000                                    16445496.0
      Under $25000                                     5333749.0

                                     Total income: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                     63830
      $25000 to $50000                                        212010
      $50,000 to $75,000                                       90440
      $75,000 to $100,000                                      46890
      Over $200000                                             30320
      Under $25000                                            418500

                                     Total income: Amount  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                        8778716
      $25000 to $50000                            7618708
      $50,000 to $75,000                          5581397
      $75,000 to $100,000                         4088124
      Over $200000                               16661515
      Under $25000                                5465515

                                     Salaries and wages in AGI: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                  57550
      $25000 to $50000                                                     194710
      $50,000 to $75,000                                                    82210
      $75,000 to $100,000                                                   42130
      Over $200000                                                          27010
      Under $25000                                                         301790

                                     Salaries and wages in AGI: Amount  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                     6833594
      $25000 to $50000                                         6847426
      $50,000 to $75,000                                       4759655
      $75,000 to $100,000                                      3333035
      Over $200000                                             8612438
      Under $25000                                             4169463

                                     Taxable interest: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                         27470
      $25000 to $50000                                             21400
      $50,000 to $75,000                                           18380
      $75,000 to $100,000                                          14180
      Over $200000                                                 21250
      Under $25000                                                 26660

                                     Taxable interest: Amount  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                              70725
      $25000 to $50000                                  23131
      $50,000 to $75,000                                24681
      $75,000 to $100,000                               22206
      Over $200000                                     289711
      Under $25000                                      21893

                                     Ordinary dividends: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                           18310
      $25000 to $50000                                               11470
      $50,000 to $75,000                                             10280
      $75,000 to $100,000                                             8250
      Over $200000                                                   16840
      Under $25000                                                   13560

                                     Ordinary dividends: Amount  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                               133761
      $25000 to $50000                                    37810
      $50,000 to $75,000                                  42529
      $75,000 to $100,000                                 42252
      Over $200000                                       668610
      Under $25000                                        30316

                                     Qualified dividends: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                            16710
      $25000 to $50000                                                 8970
      $50,000 to $75,000                                               8920
      $75,000 to $100,000                                              7250
      Over $200000                                                    15870
      Under $25000                                                    10930

                                     Qualified dividends: Amount  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                 94866
      $25000 to $50000                                     22144
      $50,000 to $75,000                                   26474
      $75,000 to $100,000                                  27896
      Over $200000                                        487588
      Under $25000                                         17715

                                     State and local income tax refunds: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                        1000
      $25000 to $50000                                                             450
      $50,000 to $75,000                                                           540
      $75,000 to $100,000                                                          240
      Over $200000                                                                1060
      Under $25000                                                                 140

                                     State and local income tax refunds: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                        1840
      $25000 to $50000                                                             355
      $50,000 to $75,000                                                           440
      $75,000 to $100,000                                                          247
      Over $200000                                                               13751
      Under $25000                                                                 109

                                     Business or profession net income: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                       13690
      $25000 to $50000                                                           48940
      $50,000 to $75,000                                                         17760
      $75,000 to $100,000                                                         9370
      Over $200000                                                                7030
      Under $25000                                                              177570

                                     Business or profession net income: Amount  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                              177401
      $25000 to $50000                                                  181132
      $50,000 to $75,000                                                109246
      $75,000 to $100,000                                                79519
      Over $200000                                                      392325
      Under $25000                                                      961580

                                     Net capital gain in AGI: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                17090
      $25000 to $50000                                                    10430
      $50,000 to $75,000                                                   9270
      $75,000 to $100,000                                                  7620
      Over $200000                                                        17090
      Under $25000                                                        12200

                                     Net capital gain in AGI: Amount  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                    155577
      $25000 to $50000                                         15349
      $50,000 to $75,000                                       28317
      $75,000 to $100,000                                      36051
      Over $200000                                           2129171
      Under $25000                                              4578

                                     Taxable individual retirement arrangement distributions: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                        7240
      $25000 to $50000                                                            5930
      $50,000 to $75,000                                                          5150
      $75,000 to $100,000                                                         3890
      Over $200000                                                                3730
      Under $25000                                                                8180

                                     Taxable individual retirement arrangement distributions: Amount  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                      204630
      $25000 to $50000                                                           60707
      $50,000 to $75,000                                                         70066
      $75,000 to $100,000                                                        67766
      Over $200000                                                              207159
      Under $25000                                                               50878

                                     Pensions and annuities in AGI: Number of returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                                      12160
      $25000 to $50000                                                          16200
      $50,000 to $75,000                                                        11550
      $75,000 to $100,000                                                        7930
      Over $200000                                                               4800
      Under $25000                                                              19660

                                     Pensions and annuities in AGI: Amount  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                                          499180
      $25000 to $50000                                              220452
      $50,000 to $75,000                                            253391
      $75,000 to $100,000                                           230510
      Over $200000                                                  300279
      Under $25000                                                  147984

                                     Number of farm returns  \
City  Size of adjusted gross income
Miami $100,000 to $200,000                            180.0
      $25000 to $50000                                150.0
      $50,000 to $75,000                               50.0
      $75,000 to $100,000                              20.0

In [236]:
# Orlando prototype total.
# Income rows are not in the original order as they are sorted by ascending order.
# This can be fixed later.
Orlando_stats=Florida_cities.loc[Florida_cities["City"]=="Orlando",:]
Orlando_stats=Orlando_stats.groupby(["City", "Size of adjusted gross income"]).sum().reset_index()
Orlando_stats.head(10)

,City,Size of adjusted gross income,Number of returns,Number of single returns,Number of joint returns,Number of head of household returns,Number with paid preparer's signature,Number of exemptions,Number of dependents,Total Number of volunteer prepared returns,Number of volunteer income tax assistance prepared returns,Number of tax counseling for the elderly prepared returns,Number of volunteer prepared returns with Earned Income Credit,Number of refund anticipation loan returns,Number of refund anticipation check returns,Number of elderly returns,Adjusted gross income (AGI),Total income: Number of returns,Total income: Amount,Salaries and wages in AGI: Number of returns,Salaries and wages in AGI: Amount,Taxable interest: Number of returns,Taxable interest: Amount,Ordinary dividends: Number of returns,Ordinary dividends: Amount,Qualified dividends: Number of returns,Qualified dividends: Amount,State and local income tax refunds: Number of returns,State and local income tax refunds: Number of returns,Business or profession net income: Number of returns,Business or profession net income: Amount,Net capital gain in AGI: Number of returns,Net capital gain in AGI: Amount,Taxable individual retirement arrangement distributions: Number of returns,Taxable individual retirement arrangement distributions: Amount,Pensions and annuities in AGI: Number of returns,Pensions and annuities in AGI: Amount,Number of farm returns,Unemployment compensation: Number of returns,Unemployment compensation: Amount,Taxable Social Security benefits: Number or returns,Taxable Social Security benefits: Amount,Partnership/S-corp net income: Number of returns,Partnership/S-corp net income: Amount,Total statuory adjustments: Number of returns,Total statuory adjustments: Amount,Educator expenses: Number of returns,Educator expenses: Amount,Self-employed (Keogh) retirement plans: Number of returns,Self-employed (Keogh) retirement plans: Amount,Self-employed health insurance deduction: Number of returns,Self-employed health insurance deduction: Amount,Individual retirement arrangement payments: Number of returns,Individual retirement arrangement payments: Amount,Student loan interest deduction: Number of returns,Student loan interest deduction: Amount,Tuition and fees deduction: Number of returns,Tuition and fees deduction: Amount,Domestic production activities deduction: Number of returns,Domestic production activities deduction: Amount,Total itemized deductions: Number of returns,Total itemized deductions: Amount,Total itemized deductions: Amount of AGI,Total medical and dental expenses deduction: Number of returns,Total medical and dental expenses deduction: Amount,State and local income taxes: Number of returns,State and local income taxes: Amount,State and local general sales taxes: Number of returns,State and local general sales taxes: Amount,Real estate taxes: Number of returns,Real estate taxes: Amount,Personal property taxes: Number of returns,Personal property taxes: Amount,Total taxes paid: Number of returns,Total taxes paid: Amount,Home mortgage interest paid: Number of returns,Home mortgage interest paid: Amount,Home mortgage interest paid from personal seller: Number of returns,Home mortgage interest paid from personal seller: Amount,Deductible points: Number of returns,Deductible points: Amount,Qualified mortgage insurance premiums: Number of returns,Qualified mortgage insurance premiums: Amount,Investment interest paid: Number of returns,Investment interest paid: Amount,Total charitable contributions: Number of returns,Total charitable contributions: Amount,Net limited miscellaneous deduction: Number of returns,Net limited miscellaneous deduction: Amount,Other non-limited miscellaneous deduction: Number of returns,Other non-limited miscellaneous deduction: Amount,Taxable income: Number of returns,Taxable income: Amount,Income tax before credits,ncome tax before credits: Amount,Alternative minimum tax: Number of returns,Alternative minimum tax: Amount,Excess advance premium tax credit repayment: Number of returns,Excess advance premium tax credit repayment: Amount,Total tax credits: Number of returns,Total tax credits: Amount,Foreign tax credit: Number of returns,Foreign tax credit: Amount,Child and dependent care credit: Number of returns,Child and dependent care credit: Amount,Nonrefundable education credit: Number of returns,Nonrefundable education credit: Amount,Retirement savings contributions credit: Number of returns,Retirement savings contributions credit: Amount,Child tax credit: Number of returns,Child tax credit: Amount,Residential energy tax credit: Number of returns,Residential energy tax credit: Amount,Self-employment tax: Number of returns,Self-employment tax: Amount,Total premium tax credit: Number of returns,Total premium tax credit: Amount,Advance premium tax credit: Number of returns,Advance premium tax credit: Amount,Health care individual responsibility payment: Number of returns,Health care individual responsibility payment: Amount,Total tax payments: Number of returns,Total tax payments: Amount,Earned income credit: Number of returns,Earned income credit: Amount,Excess earned income credit (refundable): Number or returns,Excess earned income credit (refundable): Amount,Additional child tax credit: Number of returns,Additional child tax credit: Amount,Refundable education credit: Number of returns,Refundable education credit: Amount,Net premium tax credit: Number of returns,Net premium tax credit: Amount,Income tax: Number of returns,Income tax: Amount,Total tax liability: Number of returns,Total tax liability: Amount,Total additional Medicare tax: Number of returns,Total additional Medicare tax: Amount,Net investment income tax: Number of returns,Net investment income tax: Amount,Tax due at time of filing: Number of returns,Tax due at time of filing: Amount,Overpayments refunded: Number of returns,Overpayments refunded: Amount
0,Orlando,"$100,000 to $200,000",35470.0,6140.0,27280.0,1840.0,17900.0,93450.0,30770.0,0,0,0,0,0.0,2270.0,8220.0,4777445.0,35470,4833753,32600,3860667,15290,20552,12290,59716,11450,43873,1370,1792,6810,90594,10430,78151,4500,121189,8330,316557,0.0,210,741,5470,127936,4920,171112,13020,56308,2010,544,340,4457,1370,11274,1420,8228,4410,5053,720,1608,180,1864,20460,480914,2818539,2310,28218,1780,11356,15330,29657,18830,78374,4140,2274,20300,121803,17660,169478,400,2459,890,714,680,701,440,706,17660,88676,6540,66884,440,6266,35440,3742519,35380,668736,1020,2131,290,1244,15300,22082,3590,2514,4270,2492,2970,4105,0,0,7140,9077,1920,1714,4590,15662,0,0,360,1562,500,1035,35130,706611,0,0,0,0,0,0,2640,2422,0,0,35310,646813,35350,667780,320,88,20,23,12590,65041,21940,96623
1,Orlando,$25000 to $50000,123530.0,64060.0,25630.0,30010.0,58470.0,229090.0,80470.0,1350,560,790,0,1770.0,28680.0,15750.0,4380745.0,123530,4430987,114440,3967553,12470,8015,8450,17668,7220,11334,410,251,19200,83572,6470,10809,4450,42741,13020,179862,20.0,1930,5803,10090,64653,4360,45363,29760,50242,2640,631,50,481,1390,4788,2080,7331,14320,14643,570,1420,0,0,25030,432806,924827,7960,56829,1440,3318,18340,17868,12010,27798,5600,4869,23220,55393,11640,73124,350,1522,240,262,4360,6958,220,250,17650,50214,15900,186264,260,1291,118100,2209037,118410,278621,0,0,9970,6571,54770,47190,1560,230,8030,4432,13500,14002,19770,3759,27570,23439,1980,888,10650,23622,12840,53816,14110,63008,8610,5457,121090,544882,33580,72923,28110,60130,24320,32465,10800,9492,2980,2140,94560,231428,100840,262053,0,0,0,0,15580,26694,107110,306814
2,Orlando,"$50,000 to $75,000",51850.0,22710.0,20070.0,7420.0,24230.0,103400.0,31510.0,130,20,110,0,60.0,7690.0,10010.0,3160155.0,51850,3198275,47230,2690096,10730,8445,7540,21697,6730,14873,850,608,7820,50433,5930,15150,3740,49996,9080,200438,20.0,670,2426,7060,104487,3160,51368,16700,38120,2120,528,40,574,1010,5528,1560,6657,8510,9532,1020,2271,30,91,17650,332283,1086103,4310,38058,990,2872,12630,15875,12880,33488,3930,2812,17000,56178,12380,86430,320,1337,590,545,4270,7395,230,324,13730,46625,8290,92459,440,2345,51580,2088400,51530,303023,0,0,2260,3831,20230,28859,1750,303,3370,1830,4710,6015,3770,626,12770,18254,1710,1145,4730,12183,1980,8178,2650,12712,2230,2118,50970,381114,20,8,0,0,2180,2650,3570,3238,120,105,49340,274165,49960,290532,0,0,0,0,10710,26737,40600,114808
3,Orlando,"$75,000 to $100,000",27570.0,7990.0,16620.0,2420.0,13060.0,63550.0,19410.0,0,0,0,0,0.0,2750.0,6320.0,2381320.0,27570,2406248,25050,1958864,8470,8036,6150,20934,5560,14855,350,370,4680,38561,5000,18186,2920,52860,6120,167927,0.0,520,1889,4660,92164,2290,41966,8630,24928,1040,282,0,0,510,3445,750,3634,3750,4112,80,196,0,0,11780,241128,1021657,2300,22579,700,2785,8540,12910,9980,31290,2560,1689,11540,49884,9460,73821,100,562,270,215,3160,5693,30,18,9570,38148,4520,47411,40,318,27500,1711996,27470,264843,120,143,630,1930,11480,18719,1490,404,2430,1374,2670,3533,0,0,7730,11936,1150,857,2950,8112,160,507,910,3806,870,1174,27190,304647,0,0,0,0,60,79,2070,1862,0,0,27220,246117,27320,256944,0,0,0,0,7030,21877,20110,67456
4,Orlando,Over $200000,12110.0,1540.0,9900.0,360.0,8470.0,33800.0,11780.0,0,0,0,0,0.0,20.0,2990.0,5508931.0,12110,5585010,11130,3217543,8340,51362,7060,144700,6770,114372,550,4440,2620,119832,6960,433511,1480,72120,2210,117233,0.0,0,0,1500,39501,4520,1080440,4490,76079,80,21,330,8605,1370,16489,220,2150,0,0,0,0,300,8799,9410,406127,4133085,40,1758,1080,34638,7430,22906,8880,76618,1200,691,9380,140270,7820,107116,40,358,360,217,0,0,820,8370,8500,119570,1930,31748,170,3548,12100,4976694,12090,1385370,3150,14050,0,0,4820,24688,3220,15904,1180,677,0,0,0,0,0,0,400,545,2330,16140,0,0,0,0,0,0,11980,1345150,0,0,0,0,0,0,0,0,0,0,12080,1355645,12080,1402519,6220,10613,6160,16624,6000,171775,4650,64500
5,Orlando,Under $25000,215530.0,139070.0,21420.0,51880.0,111700.0,328410.0,116770.0,3190,1340,1860,460,5770.0,54240.0,24920.0,2892019.0,215530,2945569,178360,2484663,13080,6672,8490,14068,7270,8829,260,140,53460,259695,6820,3406,5140,31129,14920,113555,20.0,3090,8352,4320,8550,4260,14703,50080,53550,940,215,0,0,1880,3928,970,2902,7720,6510,2280,6335,20,253,12430,179626,210033,5130,37411,310,483,9120,5912,4960,12113,2040,1414,11260,21460,4420,28850,40,211,30,24,1000,1501,20,22,7230,15243,7820,72200,40,186,95920,563152,99220,62130,0,0,10880,2841,36040,13350,470,37,2580,823,12960,7390,11840,2065,9460,2731,280,76,38650,52779,27880,114349,28910,117824,7230,3900,201870,582884,98270,275177,86730,236143,58780,75762,21690,18871,14280,5053,74950,48774,110920,106510,0,0,0,0,18660,16946,188750,491770